nelmio_api_doc:
    documentation:
        info:
            title: Test application
            description: Test application example!
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/(?!doc|api/doc.json$) # Accepts routes under / except /doc
